# Generated by Django 5.2 on 2025-10-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
