# Generated by Django 5.2 on 2025-10-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_legajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='tutor',
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutores',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='alumnos.tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nro_doc',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
